import { Entity, Mesh, SkinnedMesh, StandardMaterial, Animator, loadGLTF, quat } from "../engine/index.js";
import { weaponGeometry } from "./models.js";
import { FLAG } from "./protocol.js";
import { MOVE } from "./data.js";

/**
 * BREACH: the other players, as skinned characters. The trooper model and its clips are generated by
 * tools/make-models.mjs and read with the engine's glTF loader. Everyone shares one skeleton, one set
 * of clips, one geometry and one material; each has an Animator of their own and a five-colour palette.
 *
 * A Trooper is driven by what the client knows about a player this frame: where they are, how fast they
 * are moving, whether they are on the ground or crouched, and where they are looking. From that it picks
 * a clip, tilts the spine to aim up or down, and hangs the weapon in the hands.
 * @module game/characters
 */

let assets = null;
/** Load the model once. Resolves to { asset, geometry, upright }. */
export async function loadCharacters(base = "assets/models/") {
    if (assets) return assets;
    const asset = await loadGLTF(base + "trooper.glb");
    assets = { asset, geometry: asset.geometry("body"), upright: asset.upright };
    return assets;
}

/** undersuit, armour plate, visor, boots: the same for everyone; slot 0 is the player's own colour */
const FIXED = [[0.09, 0.1, 0.12], [0.3, 0.32, 0.36], [0.55, 0.95, 1.0], [0.06, 0.06, 0.07]];
let shared = null;
const material = () => shared || (shared = new StandardMaterial({ palette: new Float32Array(StandardMaterial.PALETTE_SIZE * 3).fill(1), specular: 0.35, shininess: 30 }));
let weaponMaterial = null;

const qx = quat.create(), qz = quat.setAxisAngle(quat.create(), [0, 0, 1], Math.PI / 2);

export class Trooper {
    /** @param {number[]} color the player's colour */
    constructor(color) {
        const a = assets;
        this.animator = new Animator(a.asset.skeleton, a.asset.clips);
        /** place and turn this; +Y of the model is forward */
        this.root = new Entity({ name: "trooper" });
        this.root.interpolate = false;
        const mesh = new SkinnedMesh(a.geometry, material(), this.animator);
        this.palette = new Float32Array(StandardMaterial.PALETTE_SIZE * 3);
        FIXED.forEach((c, i) => this.palette.set(c, (i + 1) * 3));
        this.emissive = new Float32Array(3);
        mesh.uniforms = { u_palette: this.palette, u_emissive: this.emissive };
        this.setColor(color);
        this.body = this.root.add(new Entity({ name: "body", mesh, cullRadius: 1.4 }));
        this.body.interpolate = false;
        quat.copy(this.body.rotation, a.upright);
        if (!weaponMaterial) weaponMaterial = new StandardMaterial({ vertexColors: true, specular: 0.5 });
        this.weapon = this.root.add(new Entity({ name: "weapon", mesh: new Mesh(weaponGeometry(0), weaponMaterial) }));
        this.weapon.interpolate = false;
        this.weaponIndex = 0;
        const sk = a.asset.skeleton;
        this.spine = sk.index("spine"); this.chest = sk.index("chest");
        this.dead = 0;
        this.stride = 0;
        this.animator.play("idle", { fade: 0 });
    }

    setColor(c) { this.palette.set(c, 0); }

    /**
     * @param {number} dt
     * @param {{ x: number, y: number, z: number, yaw: number, pitch: number, flags: number, weapon: number, speed: number }} s
     * @returns {boolean} true on a frame a foot comes down (for the footstep sound)
     */
    update(dt, s) {
        const alive = (s.flags & FLAG.alive) !== 0, crouched = (s.flags & FLAG.crouched) !== 0, ground = (s.flags & FLAG.ground) !== 0, an = this.animator;
        this.root.setPosition(s.x, s.y, s.z);
        this.root.setYaw(s.yaw - Math.PI / 2);

        let step = false;
        if (!alive) { an.play("die", { loop: false, fade: 0.08 }); this.dead += dt; }
        else {
            this.dead = 0;
            if (!ground) an.play("jump", { fade: 0.12 });
            else if (crouched) an.play(s.speed > 0.6 ? "crouchwalk" : "crouch", { fade: 0.15, speed: s.speed > 0.6 ? s.speed / 3.2 : 1 });
            else if (s.speed > 4.4) an.play("run", { fade: 0.15, speed: s.speed / 7.6 });
            else if (s.speed > 0.6) an.play("walk", { fade: 0.15, speed: s.speed / 3.6 });
            else an.play("idle", { fade: 0.2 });
            if (ground && s.speed > 0.6) { this.stride += s.speed * dt; if (this.stride > 2.1) { this.stride = 0; step = true; } }
        }
        // a body lies where it fell for a couple of seconds, then is gone until its owner is back
        this.root.visible = alive || this.dead < 2.6;
        this.weapon.visible = alive;

        an.sample(dt);
        if (alive) {
            // aim up and down from the waist: half the angle at the spine, half at the chest
            const p = an.pose, half = s.pitch * 0.25, sn = Math.sin(half), cs = Math.cos(half);
            for (const joint of [this.spine, this.chest]) {
                const o = joint * 10 + 3, x = p[o], y = p[o + 1], z = p[o + 2], w = p[o + 3];
                // q = (rotation about X by pitch/2) · q
                p[o] = cs * x + sn * w; p[o + 1] = cs * y - sn * z; p[o + 2] = cs * z + sn * y; p[o + 3] = cs * w - sn * x;
            }
        }
        an.solve();

        if (alive) {
            if (s.weapon !== this.weaponIndex) { this.weaponIndex = s.weapon; this.weapon.mesh = new Mesh(weaponGeometry(s.weapon), weaponMaterial); }
            // the weapon sits in front of the right shoulder and swings about the chest as the aim tilts
            const drop = crouched ? 0.36 : 0, pivotZ = 1.17 - drop, oy = 0.36, oz = 1.36 - drop - pivotZ, c = Math.cos(s.pitch), sn = Math.sin(s.pitch);
            this.weapon.setPosition(0.17, (crouched ? 0.1 : 0) + oy * c - oz * sn, pivotZ + oy * sn + oz * c);
            quat.setAxisAngle(qx, [1, 0, 0], s.pitch);
            quat.multiply(this.weapon.rotation, qx, qz);
        }
        // spawn protection shows as a pale sheen; overcharge as a hot glow
        const e = this.emissive;
        if (s.flags & FLAG.overcharge) { e[0] = 1.5; e[1] = 0.35; e[2] = 2.0; } else if (s.flags & FLAG.protect) { e[0] = e[1] = e[2] = 0.35; } else e[0] = e[1] = e[2] = 0;
        return step;
    }

    /** where the head is, for name tags and sounds */
    headHeight(crouched) { return crouched ? MOVE.crouchHeight : MOVE.height; }
}
